version: "3.9"
services:
  web:
    build: .
    ports:
      - "8080:8080"
    entrypoint: java -jar ./app.jar --spring.rabbitmq.host=rabbit --spring.redis.host=redis --spring.datasource.url=jdbc:postgresql://postgres:5432/db --spring.datasource.username=root --spring.datasource.password=root
    depends_on:
      - redis
      - rabbitmq
      - postgres
    links:
      - redis
      - rabbitmq
      - postgres
  redis:
    image: redis
    ports:
      - "6379:6379"
  rabbitmq:
    image: nugrohosam/rabbitmq-queue
    ports:
      - "5672:5672"
      - "15672:15672"
  postgres:
    image: postgres
    ports: 
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: db
volumes:
  logvolume01: {}
